services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: senha_segura

    volumes:
      - mysql_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
    ports:
      - 8080:80
    depends_on:
      - db

volumes:
  mysql_data:
