# -*- coding: utf-8 -*-
"""Avaliação_07.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hsrzcFH4ijPXnQNbfVKwT1zDpA3FOAKn
"""

!pip install mysql-connector-python

!apt-get -y install mysql-server

!service mysql start

!mysql -e "ALTER USER 'root'@'localhost' IDENTIFIED WITH 'mysql_native_password' BY 'bd_rules';FLUSH PRIVILEGES;"

import mysql.connector

# Conectando ao banco
conn = mysql.connector.connect(
    host="localhost",
    user="root",
    password="bd_rules"
)
cursor = conn.cursor()

cursor.execute("CREATE DATABASE IF NOT EXISTS empresa")

# Switch to the 'library' database
cursor.execute("USE empresa")

# Create the 'books' table
cursor.execute('''
CREATE TABLE IF NOT EXISTS funcionarios (
    id INT AUTO_INCREMENT PRIMARY KEY,
    nome VARCHAR(100),
    salario DECIMAL(10,2)
)
''')
def calcular_bonus(salario):
    return salario * 0.1

def adicionar_funcionario(nome, salario):
    cursor.execute("INSERT INTO funcionarios (nome, salario) VALUES (%s, %s)", (nome, salario))
    conn.commit()

adicionar_funcionario('Andre Almeida', 10000.00)
adicionar_funcionario('João Silva', 15000.00)
adicionar_funcionario('Maria Santos', 20000.00)

cursor.execute("""
    SELECT nome, salario, calcular_bonus(salario) AS bonus
    FROM funcionarios
""")
for row in cursor.fetchall():
    print(row)
cursor.close()
conn.close()